spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/video_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

video-manager:
  ffmpeg-path: C:\Program Files\Git\bin\ffmpeg
  ffprobe-path: C:\Program Files\Git\bin\ffprobe