spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/video_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true