version: "3"

services:
  localdb:
    image: mysql:5.6.42
    container_name: db.local
    command: mysqld --user=root --verbose
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "video_manager"
      MYSQL_ROOT_PASSWORD: "password"
