package me.kkywalk2.videomanager.fakes

import me.kkywalk2.videomanager.members.domains.Member
import me.kkywalk2.videomanager.members.services.ports.MemberRepository
import java.util.*

class FakeMemberRepository : MemberRepository {

    private val members = mutableListOf<Member>()
    private var autogeneratedId = 0L

    override fun findById(id: Long): Optional<Member> {
        return Optional.ofNullable(members.firstOrNull { it.id == id })
    }

    override fun findByEmail(email: String): Optional<Member> {
        return Optional.ofNullable(members.firstOrNull { it.email == email })
    }

    override fun save(member: Member): Member {
        return if (member.id == 0L) {
            val newMember = member.copy(id = ++autogeneratedId)
            members.add(newMember)
            newMember
        } else {
            members.removeIf { it.id == member.id }
            members.add(member)
            member
        }
    }
}